apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  labels:
    update: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: pavan8767/harness-ci:<+pipeline.sequenceId>
        name: guestbook-ui
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
